[tool.black]
line-length = 94

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 94
disable = [
    "C0103", # (invalid-name)
    "C0114", # (missing-module-docstring)
    "C0115", # (missing-class-docstring)
    "C0116", # (missing-function-docstring)
]

[tool.isort]
profile = "black"
line_length = 94
known_msgs = "std_msgs,sensor_msgs,geometry_msgs,visualization_msgs"
known_ros = "rospy,tf,interactive_markers"
known_first_party = "stack_of_tasks"
sections = "FUTURE,STDLIB,THIRDPARTY,ROS,MSGS,FIRSTPARTY,LOCALFOLDER"
no_lines_before = "MSGS"
